version: '3.7'

services:
  db:
    image: postgres:11.2
    container_name: db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/postgresql/data
    ports:
      - 6003:5432
    environment:
      - POSTGRES_DB=${database_name}
      - POSTGRES_PASSWORD=${database_password}
    restart: always

  cache:
    image: 'bitnami/redis:latest'
    container_name: cache
    restart: always
    ports:
      - '6380:6379'
    volumes:
      - cache:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=${redis_password}
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    volumes:
      - .:/app # Mount the source code
    ports:
      - '8080:8080'
    depends_on:
      - db
      - cache
    command: air # or "reflex -r '.*\\.go$' -s -- sh -c 'go run main.go'"
    restart: always

volumes:
  db:
  cache:
