CREATE USER aro_user WITH PASSWORD 'db1234@aro2024';
ALTER USER aro_user WITH SUPERUSER;
ALTER ROLE aro_user CREATEROLE CREATEDB;

CREATE DATABASE aro;
GRANT ALL PRIVILEGES ON DATABASE aro to aro_user;